version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/kib-task
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TMDB_API_KEY=170675d1d997bfda30198b9f4a7362fd
      - JWT_SECRET=newSecret
      - NODE_ENV=dev
    depends_on:
      - postgres
      - redis
    entrypoint: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:prod
      "

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  pgdata:
