version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:123@postgres:5432/nest
      - JWT_SECRET=newSecret
      - TMDB_API_KEY=170675d1d997bfda30198b9f4a7362fd
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge